openapi: 3.1.0
info:
  title: Teatro CLI
  version: "0.1.0"
  description: |
    HTTP façade for the Teatro RenderCLI. Converts scripts, scores, or storyboards
    into various render targets (HTML, SVG, PNG, Markdown, Codex, animated SVG,
    Csound .csd, or Universal MIDI Packet).
servers:
  - url: http://localhost:8080
paths:
  /render:
    post:
      summary: Render a Teatro view
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RenderRequest"
      responses:
        "200":
          description: Rendered output or file path
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RenderResponse"
components:
  schemas:
    RenderRequest:
      type: object
      properties:
        input:
          type: string
          description: Path to input file (e.g., .fountain, .ly, .mid/.midi, .ump, .csd, .storyboard, .session)
        format:
          type: string
          enum: [html, svg, png, markdown, codex, svgAnimated, csound, ump]
          description: Target output format
        output:
          type: string
          description: Destination path; if omitted, result returns inline
        watch:
          type: boolean
          default: false
          description: Re-render on file changes (server keeps connection open)
        forceFormat:
          type: boolean
          default: false
          description: Ignore mismatched output extension and format
        width:
          type: integer
          description: Override output width
        height:
          type: integer
          description: Override output height
      required: []
    RenderResponse:
      type: object
      properties:
        content:
          type: string
          description: Rendered output; binary formats are Base64-encoded
        outputPath:
          type: string
          description: Path where the file was written, if any
